apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: heartbeat
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: heartbeat
  minReplicas: 1
  maxReplicas: 10
  #targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
