apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  labels:
    app: heartbeat-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: heartbeat-api
